/*==========================================================================*\
 |  _LMSInstance.java
 |*-------------------------------------------------------------------------*|
 |  Created by eogenerator
 |  DO NOT EDIT.  Make changes to LMSInstance.java instead.
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006-2012 Virginia Tech
 |
 |  This file is part of Web-CAT.
 |
 |  Web-CAT is free software; you can redistribute it and/or modify
 |  it under the terms of the GNU Affero General Public License as published
 |  by the Free Software Foundation; either version 3 of the License, or
 |  (at your option) any later version.
 |
 |  Web-CAT is distributed in the hope that it will be useful,
 |  but WITHOUT ANY WARRANTY; without even the implied warranty of
 |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |  GNU General Public License for more details.
 |
 |  You should have received a copy of the GNU Affero General Public License
 |  along with Web-CAT; if not, see <http://www.gnu.org/licenses/>.
\*==========================================================================*/

package org.webcat.core.lti;

import com.webobjects.eoaccess.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;
import er.extensions.eof.ERXEOControlUtilities;
import er.extensions.eof.ERXKey;
import org.apache.log4j.Logger;
import org.webcat.core.EOBasedKeyGenerator;
import org.webcat.woextensions.WCFetchSpecification;

// -------------------------------------------------------------------------
/**
 * An automatically generated EOGenericRecord subclass.  DO NOT EDIT.
 * To change, use EOModeler, or make additions in
 * LMSInstance.java.
 *
 * @author Generated by eogenerator
 * @version version suppressed to control auto-generation
 */
public abstract class _LMSInstance
    extends org.webcat.core.EOBase
{
    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new _LMSInstance object.
     */
    public _LMSInstance()
    {
        super();
    }


    // ----------------------------------------------------------
    /**
     * A static factory method for creating a new
     * LMSInstance object given required
     * attributes and relationships.
     * @param editingContext The context in which the new object will be
     * inserted
     * @param consumerKeyValue
     * @param consumerSecretValue
     * @param authenticationDomainValue
     * @param lmsTypeValue
     * @return The newly created object
     */
    public static LMSInstance create(
        EOEditingContext editingContext,
        String consumerKeyValue,
        String consumerSecretValue,
        org.webcat.core.AuthenticationDomain authenticationDomainValue,
        org.webcat.core.lti.LMSType lmsTypeValue
        )
    {
        LMSInstance eoObject = (LMSInstance)
            EOUtilities.createAndInsertInstance(
                editingContext,
                _LMSInstance.ENTITY_NAME);
        eoObject.setConsumerKey(consumerKeyValue);
        eoObject.setConsumerSecret(consumerSecretValue);
        eoObject.setAuthenticationDomainRelationship(authenticationDomainValue);
        eoObject.setLmsTypeRelationship(lmsTypeValue);
        return eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Get a local instance of the given object in another editing context.
     * @param editingContext The target editing context
     * @param eo The object to import
     * @return An instance of the given object in the target editing context
     */
    public static LMSInstance localInstance(
        EOEditingContext editingContext, LMSInstance eo)
    {
        return (eo == null)
            ? null
            : (LMSInstance)EOUtilities.localInstanceOfObject(
                editingContext, eo);
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static LMSInstance forId(
        EOEditingContext ec, int id)
    {
        LMSInstance obj = null;
        if (id > 0)
        {
            NSArray<LMSInstance> objects =
                objectsMatchingValues(ec, "id", new Integer(id));
            if (objects != null && objects.count() > 0)
            {
                obj = objects.objectAtIndex(0);
            }
        }
        return obj;
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static LMSInstance forId(
        EOEditingContext ec, EOGlobalID id)
    {
        return (LMSInstance)ec.faultForGlobalID(id, ec);
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static LMSInstance forId(
        EOEditingContext ec, String id)
    {
        return forId(ec, er.extensions.foundation.ERXValueUtilities.intValue(id));
    }


    //~ Constants (for key names) .............................................

    // Attributes ---
    public static final String CONSUMER_KEY_KEY = "consumerKey";
    public static final ERXKey<String> consumerKey =
        new ERXKey<String>(CONSUMER_KEY_KEY);
    public static final String CONSUMER_SECRET_KEY = "consumerSecret";
    public static final ERXKey<String> consumerSecret =
        new ERXKey<String>(CONSUMER_SECRET_KEY);
    public static final String URL_KEY = "url";
    public static final ERXKey<String> url =
        new ERXKey<String>(URL_KEY);
    // To-one relationships ---
    public static final String AUTHENTICATION_DOMAIN_KEY = "authenticationDomain";
    public static final ERXKey<org.webcat.core.AuthenticationDomain> authenticationDomain =
        new ERXKey<org.webcat.core.AuthenticationDomain>(AUTHENTICATION_DOMAIN_KEY);
    public static final String LMS_TYPE_KEY = "lmsType";
    public static final ERXKey<org.webcat.core.lti.LMSType> lmsType =
        new ERXKey<org.webcat.core.lti.LMSType>(LMS_TYPE_KEY);
    // To-many relationships ---
    public static final String COURSE_OFFERINGS_KEY = "courseOfferings";
    public static final ERXKey<org.webcat.core.CourseOffering> courseOfferings =
        new ERXKey<org.webcat.core.CourseOffering>(COURSE_OFFERINGS_KEY);
    public static final String LMS_IDENTITIES_KEY = "lmsIdentities";
    public static final ERXKey<org.webcat.core.lti.LMSIdentity> lmsIdentities =
        new ERXKey<org.webcat.core.lti.LMSIdentity>(LMS_IDENTITIES_KEY);
    // Fetch specifications ---
    public static final String ENTITY_NAME = "LMSInstance";

    public transient final EOBasedKeyGenerator generateKey =
        new EOBasedKeyGenerator(this);


    //~ Methods ...............................................................

    // ----------------------------------------------------------
    /**
     * Get a local instance of this object in another editing context.
     * @param editingContext The target editing context
     * @return An instance of this object in the target editing context
     */
    public LMSInstance localInstance(EOEditingContext editingContext)
    {
        return (LMSInstance)EOUtilities.localInstanceOfObject(
            editingContext, this);
    }


    // ----------------------------------------------------------
    /**
     * Refetch this object from the database.
     * @param editingContext The target editing context
     * @return An instance of this object in the target editing context
     */
    public LMSInstance refetch(EOEditingContext editingContext)
    {
        return (LMSInstance)refetchObjectFromDBinEditingContext(
            editingContext);
    }


    // ----------------------------------------------------------
    /**
     * Get a list of changes between this object's current state and the
     * last committed version.
     * @return a dictionary of the changes that have not yet been committed
     */
    @SuppressWarnings("unchecked")
    public NSDictionary<String, Object> changedProperties()
    {
        return changesFromSnapshot(
            editingContext().committedSnapshotForObject(this));
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>id</code> value.
     * @return the value of the attribute
     */
    public Number id()
    {
        try
        {
            return (Number)EOUtilities.primaryKeyForObject(
                editingContext() , this).objectForKey("id");
        }
        catch (Exception e)
        {
            return er.extensions.eof.ERXConstant.ZeroInteger;
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>consumerKey</code> value.
     * @return the value of the attribute
     */
    public String consumerKey()
    {
        return (String)storedValueForKey( "consumerKey" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>consumerKey</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setConsumerKey( String value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setConsumerKey("
                + value + "): was " + consumerKey() );
        }
        takeStoredValueForKey( value, "consumerKey" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>consumerSecret</code> value.
     * @return the value of the attribute
     */
    public String consumerSecret()
    {
        return (String)storedValueForKey( "consumerSecret" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>consumerSecret</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setConsumerSecret( String value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setConsumerSecret("
                + value + "): was " + consumerSecret() );
        }
        takeStoredValueForKey( value, "consumerSecret" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>url</code> value.
     * @return the value of the attribute
     */
    public String url()
    {
        return (String)storedValueForKey( "url" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>url</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setUrl( String value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setUrl("
                + value + "): was " + url() );
        }
        takeStoredValueForKey( value, "url" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>authenticationDomain</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.core.AuthenticationDomain authenticationDomain()
    {
        return (org.webcat.core.AuthenticationDomain)storedValueForKey( "authenticationDomain" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>authenticationDomain</code>
     * relationship (DO NOT USE--instead, use
     * <code>setAuthenticationDomainRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setAuthenticationDomain( org.webcat.core.AuthenticationDomain value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setAuthenticationDomain("
                + value + "): was " + authenticationDomain() );
        }
        takeStoredValueForKey( value, "authenticationDomain" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>authenticationDomain</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setAuthenticationDomainRelationship(
        org.webcat.core.AuthenticationDomain value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setAuthenticationDomainRelationship("
                + value + "): was " + authenticationDomain() );
        }
        if ( value == null )
        {
            org.webcat.core.AuthenticationDomain object = authenticationDomain();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "authenticationDomain" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "authenticationDomain" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>lmsType</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.core.lti.LMSType lmsType()
    {
        return (org.webcat.core.lti.LMSType)storedValueForKey( "lmsType" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>lmsType</code>
     * relationship (DO NOT USE--instead, use
     * <code>setLmsTypeRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setLmsType( org.webcat.core.lti.LMSType value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setLmsType("
                + value + "): was " + lmsType() );
        }
        takeStoredValueForKey( value, "lmsType" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>lmsType</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setLmsTypeRelationship(
        org.webcat.core.lti.LMSType value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setLmsTypeRelationship("
                + value + "): was " + lmsType() );
        }
        if ( value == null )
        {
            org.webcat.core.lti.LMSType object = lmsType();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "lmsType" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "lmsType" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>courseOfferings</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<org.webcat.core.CourseOffering> courseOfferings()
    {
        return (NSArray<org.webcat.core.CourseOffering>)
            storedValueForKey("courseOfferings");
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>courseOfferings</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setCourseOfferings(
        NSMutableArray<org.webcat.core.CourseOffering>  value)
    {
        if (log.isDebugEnabled())
        {
            log.debug("setCourseOfferings("
                + value + "): was " + courseOfferings());
        }
        takeStoredValueForKey(value, "courseOfferings");
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>courseOfferings</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToCourseOfferingsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToCourseOfferings( org.webcat.core.CourseOffering value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToCourseOfferings("
                + value + "): was " + courseOfferings() );
        }
        NSMutableArray<org.webcat.core.CourseOffering> array =
            (NSMutableArray<org.webcat.core.CourseOffering>)courseOfferings();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>courseOfferings</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromCourseOfferingsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromCourseOfferings( org.webcat.core.CourseOffering value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromCourseOfferings("
                + value + "): was " + courseOfferings() );
        }
        NSMutableArray<org.webcat.core.CourseOffering> array =
            (NSMutableArray<org.webcat.core.CourseOffering>)courseOfferings();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>courseOfferings</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToCourseOfferingsRelationship( org.webcat.core.CourseOffering value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToCourseOfferingsRelationship("
                + value + "): was " + courseOfferings() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "courseOfferings" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>courseOfferings</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromCourseOfferingsRelationship( org.webcat.core.CourseOffering value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromCourseOfferingsRelationship("
                + value + "): was " + courseOfferings() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "courseOfferings" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>courseOfferings</code> relationship.
     *
     * @return The new entity
     */
    public org.webcat.core.CourseOffering createCourseOfferingsRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createCourseOfferingsRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "CourseOffering" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "courseOfferings" );
        return (org.webcat.core.CourseOffering)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>courseOfferings</code> relationship.
     *
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteCourseOfferingsRelationship( org.webcat.core.CourseOffering value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteCourseOfferingsRelationship("
                + value + "): was " + courseOfferings() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "courseOfferings" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>courseOfferings</code> relationship.
     */
    public void deleteAllCourseOfferingsRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllCourseOfferingsRelationships(): was "
                + courseOfferings() );
        }
        for (org.webcat.core.CourseOffering object : courseOfferings())
        {
            deleteCourseOfferingsRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>lmsIdentities</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<org.webcat.core.lti.LMSIdentity> lmsIdentities()
    {
        return (NSArray<org.webcat.core.lti.LMSIdentity>)
            storedValueForKey("lmsIdentities");
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>lmsIdentities</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setLmsIdentities(
        NSMutableArray<org.webcat.core.lti.LMSIdentity>  value)
    {
        if (log.isDebugEnabled())
        {
            log.debug("setLmsIdentities("
                + value + "): was " + lmsIdentities());
        }
        takeStoredValueForKey(value, "lmsIdentities");
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>lmsIdentities</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToLmsIdentitiesRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToLmsIdentities( org.webcat.core.lti.LMSIdentity value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToLmsIdentities("
                + value + "): was " + lmsIdentities() );
        }
        NSMutableArray<org.webcat.core.lti.LMSIdentity> array =
            (NSMutableArray<org.webcat.core.lti.LMSIdentity>)lmsIdentities();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>lmsIdentities</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromLmsIdentitiesRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromLmsIdentities( org.webcat.core.lti.LMSIdentity value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromLmsIdentities("
                + value + "): was " + lmsIdentities() );
        }
        NSMutableArray<org.webcat.core.lti.LMSIdentity> array =
            (NSMutableArray<org.webcat.core.lti.LMSIdentity>)lmsIdentities();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>lmsIdentities</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToLmsIdentitiesRelationship( org.webcat.core.lti.LMSIdentity value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToLmsIdentitiesRelationship("
                + value + "): was " + lmsIdentities() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "lmsIdentities" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>lmsIdentities</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromLmsIdentitiesRelationship( org.webcat.core.lti.LMSIdentity value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromLmsIdentitiesRelationship("
                + value + "): was " + lmsIdentities() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "lmsIdentities" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>lmsIdentities</code> relationship.
     *
     * @return The new entity
     */
    public org.webcat.core.lti.LMSIdentity createLmsIdentitiesRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createLmsIdentitiesRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "LMSIdentity" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "lmsIdentities" );
        return (org.webcat.core.lti.LMSIdentity)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>lmsIdentities</code> relationship.
     *
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteLmsIdentitiesRelationship( org.webcat.core.lti.LMSIdentity value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteLmsIdentitiesRelationship("
                + value + "): was " + lmsIdentities() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "lmsIdentities" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>lmsIdentities</code> relationship.
     */
    public void deleteAllLmsIdentitiesRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllLmsIdentitiesRelationships(): was "
                + lmsIdentities() );
        }
        for (org.webcat.core.lti.LMSIdentity object : lmsIdentities())
        {
            deleteLmsIdentitiesRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a fetch specification.
     *
     * @param context The editing context to use
     * @param fspec The fetch specification to use
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<LMSInstance> objectsWithFetchSpecification(
        EOEditingContext context,
        EOFetchSpecification fspec)
    {
        return context.objectsWithFetchSpecification(fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<LMSInstance> allObjects(
        EOEditingContext context)
    {
        return objectsMatchingQualifier(context, null, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<LMSInstance> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier)
    {
        return objectsMatchingQualifier(context, qualifier, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier and sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings The sort orderings to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<LMSInstance> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        WCFetchSpecification<LMSInstance> fspec =
            new WCFetchSpecification<LMSInstance>(
                ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        return objectsWithFetchSpecification(context, fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a qualifier, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings the sort orderings
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static LMSInstance firstObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        WCFetchSpecification<LMSInstance> fspec =
            new WCFetchSpecification<LMSInstance>(
                ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        fspec.setFetchLimit(1);
        NSArray<LMSInstance> objects =
            objectsWithFetchSpecification(context, fspec);
        return (objects.size() > 0)
            ? objects.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the single entity that was retrieved
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static LMSInstance uniqueObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier) throws EOUtilities.MoreThanOneException
    {
        NSArray<LMSInstance> objects =
            objectsMatchingQualifier(context, qualifier);
        if (objects.size() > 1)
        {
            String msg = "fetching LMSInstance";
            try
            {
                if (qualifier != null)
                {
                    msg += " where " + qualifier;
                }
                msg += ", result = " + objects;
            }
            catch (Exception e)
            {
                log.error("Exception building MoreThanOneException message, "
                    + "contents so far: " + msg, e);
            }
            throw new EOUtilities.MoreThanOneException(msg);
        }
        return (objects.size() > 0)
            ? objects.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<LMSInstance> objectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, (String)key);
        }

        return objectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<LMSInstance> objectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return EOUtilities.objectsMatchingValues(context, ENTITY_NAME,
            keysAndValues);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static LMSInstance firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, (String)key);
        }

        return firstObjectMatchingValues(
            context, sortOrderings, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieves the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static LMSInstance firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        NSDictionary<String, Object> keysAndValues)
    {
        WCFetchSpecification<LMSInstance> fspec =
            new WCFetchSpecification<LMSInstance>(
                ENTITY_NAME,
                EOQualifier.qualifierToMatchAllValues(keysAndValues),
                sortOrderings);
        fspec.setUsesDistinct(true);
        fspec.setFetchLimit(1);

        NSArray<LMSInstance> objects =
            objectsWithFetchSpecification( context, fspec );

        if ( objects.count() == 0 )
        {
            return null;
        }
        else
        {
            return objects.objectAtIndex(0);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static LMSInstance uniqueObjectMatchingValues(
        EOEditingContext context,
        Object... keysAndValues) throws EOUtilities.MoreThanOneException
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, (String)key);
        }

        return uniqueObjectMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve an object using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static LMSInstance uniqueObjectMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
        throws EOUtilities.MoreThanOneException
    {
        try
        {
            return (LMSInstance)EOUtilities.objectMatchingValues(
                context, ENTITY_NAME, keysAndValues);
        }
        catch (EOObjectNotAvailableException e)
        {
            return null;
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return the count of all objects
     */
    public static int countOfAllObjects(EOEditingContext context)
    {
        return countOfObjectsMatchingQualifier(context, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects that match a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the count of objects matching the qualifier
     */
    public static int countOfObjectsMatchingQualifier(
        EOEditingContext context, EOQualifier qualifier)
    {
        return ERXEOControlUtilities.objectCountWithQualifier(
                context, ENTITY_NAME, qualifier);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the count of objects that match the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value "
                + "corresponding to every key that was passed. Args = "
                + java.util.Arrays.toString(keysAndValues));
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (key == null)
            {
                throw new IllegalArgumentException(
                    "Found null where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }
            else if (!(key instanceof String))
            {
                throw new IllegalArgumentException(
                    "Found a " + key.getClass().getName() + " [" + key + "]"
                    + " where a String key was expected, arguments = "
                    + java.util.Arrays.toString(keysAndValues));
            }

            valueDictionary.setObjectForKey(value, (String)key);
        }

        return countOfObjectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a dictionary of keys and values to
     * match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the count of objects that matched the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return countOfObjectsMatchingQualifier(context,
                EOQualifier.qualifierToMatchAllValues(keysAndValues));
    }


    // ----------------------------------------------------------
    /**
     * Produce a string representation of this object.  This implementation
     * calls UserPresentableDescription(), which uses WebObjects' internal
     * mechanism to print out the visible fields of this object.  Normally,
     * subclasses would override userPresentableDescription() to change
     * the way the object is printed.
     *
     * @return A string representation of the object's value
     */
    public String toString()
    {
        return userPresentableDescription();
    }


    // ----------------------------------------------------------
    /**
     * Hack to workaround bugs in ERXEOAccessUtilities.reapplyChanges().
     *
     * @param value the new value of the key
     * @param key the key to access
     */
    public void takeValueForKey(Object value, String key)
    {
        // if (ERXValueUtilities.isNull(value))
        if (value == NSKeyValueCoding.NullValue
            || value instanceof NSKeyValueCoding.Null)
        {
            value = null;
        }

        if (value instanceof NSData)
        {
            super.takeStoredValueForKey(value, key);
        }
        else
        {
            super.takeValueForKey(value, key);
        }
    }


    //~ Instance/static variables .............................................

    static Logger log = Logger.getLogger(LMSInstance.class);
}
