/*==========================================================================*\
 |  _PasswordChangeRequest.java
 |*-------------------------------------------------------------------------*|
 |  Created by eogenerator
 |  DO NOT EDIT.  Make changes to PasswordChangeRequest.java instead.
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006 Virginia Tech
 |
 |  This file is part of Web-CAT.
 |
 |  Web-CAT is free software; you can redistribute it and/or modify
 |  it under the terms of the GNU General Public License as published by
 |  the Free Software Foundation; either version 2 of the License, or
 |  (at your option) any later version.
 |
 |  Web-CAT is distributed in the hope that it will be useful,
 |  but WITHOUT ANY WARRANTY; without even the implied warranty of
 |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |  GNU General Public License for more details.
 |
 |  You should have received a copy of the GNU General Public License
 |  along with Web-CAT; if not, write to the Free Software
 |  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 |
 |  Project manager: Stephen Edwards <edwards@cs.vt.edu>
 |  Virginia Tech CS Dept, 660 McBryde Hall (0106), Blacksburg, VA 24061 USA
 \*==========================================================================*/

package net.sf.webcat.core;

import com.webobjects.foundation.*;
import com.webobjects.eocontrol.*;
import java.util.Enumeration;

// -------------------------------------------------------------------------
/**
 * An automatically generated EOGenericRecord subclass.  DO NOT EDIT.
 * To change, use EOModeler, or make additions in
 * PasswordChangeRequest.java.
 *
 * @author Generated by eogenerator
 * @version version suppressed to control auto-generation
 */
public abstract class _PasswordChangeRequest
    extends er.extensions.ERXGenericRecord
{
    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new _PasswordChangeRequest object.
     */
    public _PasswordChangeRequest()
    {
        super();
    }


    //~ Constants (for key names) .............................................

    // Attributes ---
    public static final String CODE_KEY = "code";
    public static final String EXPIRE_TIME_KEY = "expireTime";
    // To-one relationships ---
    public static final String USER_KEY = "user";
    // To-many relationships ---
    // Fetch specifications ---
    public static final String CODE_FSPEC = "code";
    public static final String EXPIRED_BEFORE_FSPEC = "expiredBefore";
    public static final String USER_FSPEC = "user";
    public static final String ENTITY_NAME = "PasswordChangeRequest";


    //~ Methods ...............................................................

    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>code</code> value.
     * @return the value of the attribute
     */
    public String code()
    {
        return (String)storedValueForKey( "code" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>code</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setCode( String value )
    {
        takeStoredValueForKey( value, "code" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>expireTime</code> value.
     * @return the value of the attribute
     */
    public NSTimestamp expireTime()
    {
        return (NSTimestamp)storedValueForKey( "expireTime" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>expireTime</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setExpireTime( NSTimestamp value )
    {
        takeStoredValueForKey( value, "expireTime" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve object according to the <code>Code</code>
     * fetch specification.
     *
     * @param context The editing context to use
     * @param codeBinding fetch spec parameter
     * @return an NSArray of the entities retrieved
     */
    public static NSArray objectsForCode(
            EOEditingContext context,
            String codeBinding
        )
    {
        EOFetchSpecification spec = EOFetchSpecification
            .fetchSpecificationNamed( "code", "PasswordChangeRequest" );

        NSMutableDictionary bindings = new NSMutableDictionary();

        if ( codeBinding != null )
            bindings.setObjectForKey( codeBinding,
                                      "code" );
        spec = spec.fetchSpecificationWithQualifierBindings( bindings );

        return context.objectsWithFetchSpecification( spec );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve object according to the <code>ExpiredBefore</code>
     * fetch specification.
     *
     * @param context The editing context to use
     * @param timeBinding fetch spec parameter
     * @return an NSArray of the entities retrieved
     */
    public static NSArray objectsForExpiredBefore(
            EOEditingContext context,
            NSTimestamp timeBinding
        )
    {
        EOFetchSpecification spec = EOFetchSpecification
            .fetchSpecificationNamed( "expiredBefore", "PasswordChangeRequest" );

        NSMutableDictionary bindings = new NSMutableDictionary();

        if ( timeBinding != null )
            bindings.setObjectForKey( timeBinding,
                                      "time" );
        spec = spec.fetchSpecificationWithQualifierBindings( bindings );

        return context.objectsWithFetchSpecification( spec );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve object according to the <code>User</code>
     * fetch specification.
     *
     * @param context The editing context to use
     * @param userBinding fetch spec parameter
     * @return an NSArray of the entities retrieved
     */
    public static NSArray objectsForUser(
            EOEditingContext context,
            net.sf.webcat.core.User userBinding
        )
    {
        EOFetchSpecification spec = EOFetchSpecification
            .fetchSpecificationNamed( "user", "PasswordChangeRequest" );

        NSMutableDictionary bindings = new NSMutableDictionary();

        if ( userBinding != null )
            bindings.setObjectForKey( userBinding,
                                      "user" );
        spec = spec.fetchSpecificationWithQualifierBindings( bindings );

        return context.objectsWithFetchSpecification( spec );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>user</code>
     * relationship.
     * @return the entity in the relationship
     */
    public net.sf.webcat.core.User user()
    {
        return (net.sf.webcat.core.User)storedValueForKey( "user" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>user</code>
     * relationship (DO NOT USE--instead, use
     * <code>setUserRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setUser( net.sf.webcat.core.User value )
    {
        takeStoredValueForKey( value, "user" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>user</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setUserRelationship(
        net.sf.webcat.core.User value )
    {
        if ( value == null )
        {
            net.sf.webcat.core.User object = user();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "user" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "user" );
        }
    }


}
